language: python
python:
  - "3.6"
install:
  - pip install python-coveralls nosexcover
  - cd python
  - pip install -e ."[test]"
  - cd ../javascript
  - nvm install 10.15
  - npm i
  - cd ..
script:
  - cd python
  - python -m nose --with-doctest --with-xcoverage --cover-package=pychatl
  - coveralls
  - cd ../javascript
  - npm test
