language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install codecov nosexcover
  - cd python
  - pip install -e ."[test]"
  - cd ../javascript
  - nvm install 10.15
  - npm i
  - cd ..
script:
  - cd python
  - python -m nose --with-doctest --with-xcoverage --cover-package=pychatl
  - cd ../javascript
  - npm test
  - npm run report
after_success:
  - codecov
